[build]
  publish = ".next"
  command = "npm ci && npm run build"  # npm ci aniqroq versiyalarni o'rnatadi

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.x"  # Node.js versiyasini belgilash
  NPM_FLAGS = "--force"