export const YILLIK_REJA = [
  {
    bolim: "MPTS QURILMALARI",
    ishlar: [
      {"ish": "Asosiy ARM DSP  dan rezerv ARM  DSP ga o'tishning to'g'riligini DSP bilan birgalikda tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNS, DSP", "jurnal": "DU-46,SHU-2", "nsh": "№7"},
      {"ish": "Printerning tashqi tomoni va ichki tomonini tozalash.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNS,elektromexanik, serviz ishchisi", "jurnal": "SHU-2", "nsh": "№9"},
      {"ish": "Kompyuter tizimli blokining ichki qismini tozalash.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS,SHN, serviz ishchisi", "jurnal": "DU-46,SHU-2", "nsh": "№10"},
      {"ish": "MPTS uchun mo'ljallangan zaxira platalar va boshqa zaxira uskunalarning mavjudligini tasdiqlangan ro'yxatga muvofiqligini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "№16"},
      {"ish": "Uskunalar joylashtirilgan shkaflarning tashqi qismini tozalash, shkaflarning  ichki qismini,montaj tomonini ko'zdan kechirish, barcha ulanish razyomlarini mahkam o'rnatilganligini tekshirish, shkaflarning ichki tomonini tozalash.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS,SHN, SHNM", "jurnal": "SHU-2", "nsh": "№20"},
      {"ish": "Stansiya navbatchisi bilan birgalikda ishlayotgan markaziy protsessor qurilmasidan rezerv markaziy protsessor qurilmasiga o'tishning to'g'riligini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNS", "jurnal": "DU-46,SHU-2", "nsh": "№21"},
      {"ish": "Kabelning barcha tolalari(жила), shu jumladan zaxira tolalari \"yer\"ga nisbatan izolyatsiya qarshiligi o'lchanadi. Bunda yo'l usti qurilmalari tomondan montaj minimal darajada ajratiladi, stansiya tomondagi ulangan joyida esa kabel to'liq o'chiriladi.", "davriylik": "Bir yilda ikki marta (Bahor va kuzda)", "bajaruvchi": "SHNS,SHN, SHNM", "jurnal": "SHU-64,SHU-2", "nsh": "№23"},
      {"ish": "Kabel ekranining \"yer\"ga nisbatan izolyatsiya qarshiligini o'lchash va ekran butunligini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNS,SHN", "jurnal": "SHU-64,SHU-2", "nsh": "№25"},
      {"ish": "Tashqi elektr ta'minoti o'chirilgan holatda MPTSning uzluksiz quvvat manbai (UBP)dan ishlashini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNS,SHN", "jurnal": "SHU-2", "nsh": "№28"},
      {"ish": "UBP yuklamadan o'chirilgan holatda MPTS ning elektr tarmog'idan ishlashini tekshirish.(qo'lda)", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNS,SHN", "jurnal": "SHU-2", "nsh": "№29"},
    ],
  },
  {
    bolim: "ESSO QURILMALARI",
    ishlar: [
      {"ish": "Rels datchiklari, ularning mahkamlagichlari va kabel muftalarini, shuningdek svetoforlar va shkaflarni bo'yash.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNM", "jurnal": "SHU-2", "nsh": "№2.4"},
      {"ish": "Kabelli muftalarning ichki holatini tekshirish, RD va KSN NSU o'rtasidagi hamda KSN NSU bilan qabul qilish punkti (PRU UVK) o'rtasida joylashgan kabellarning kabelli muftalarda to'g'ri va ishonchli ulanganligini nazorat qilish.", "davriylik": "Bir yilda ikki marta (Bahor va kuzda)", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "№4.1"},
    ],
  },
  {
    bolim: "7.BOG'LIQLIKLAR",
    ishlar: [
      {"ish": "Stansiyalarda signalizatsiyani to'g'riligini tekshirish xamda kirish, chiqish va marshrut svetoforlarini ruxsat beruvchidan, ta'qiqlovchiga o'tishini tekshirish; signalizatsiya to'g'riligini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2 DU-46", "nsh": "NSH-01 7.1"},
      {"ish": "Peregonlarda signalizatsiyani to'g'riligini tekshirish va barcha svetoforlarni ruxsat etuvchidan, ta'qiqlovchiga o'tishini tekshirish, shuningdek  ushbu yo'riqnomani  7.3 bandiga asosan relsdan uzatiluvchi kod  signal toklarini svetoforlar ko'rsatkichi bilan taqqoslash.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS, SHN", "jurnal": "SHU-79", "nsh": "NSH-01 7.1.1"},
      {"ish": "Avtoblokirovka yo'nalishini o'zgartirish sxemasining asosiy va yordamchi rejimlarda ishlashini tekshirish:Avariyali o'zgartirish simlarini nazorat qilish bilan", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHNS,SHN, DSP (DNS)", "jurnal": "DU-46,SHU-2", "nsh": "NSH-01 7.1.2"},
      {"ish": "Kirish, chiqish va marshrut svetoforlarini, barcha band bo'lgan izolyatsiyalangan uchastkalar va qabul qiluvchi yo'llarga ochilmasligini tekshirish; uzoqlashish uchastkasi band bo'lganda izolyatsiyalangan uchastkalardan signal ochilmasligini tekshirish, avtoblokirovkada noto'g'ri yo'nalish tomon signal ochilmasligini tekshirish, poluavtoblokirovkada  rozilik va yetib kelish blokirovka  signallarini yo'qligi.Qurilmalarni yo'nalishdan chiqarishdan ushlab turish vaqtini tekshirish.Izolyatsiya uchastkalarni su'niy bo'shatish orqali ushlab turish vaqtini tekshirish. Marshrut markazlashtirishdagi yordamchi vositalar bilan,bir yo'llik uchastkalarda xarakat yo'nalishini o'zgartirishini tekshirish. Su'niy band qilingan izolyatsiya uchastkalar xolatida, belgilanmagan marshrutda  strelkalarni aylanmasligini tekshirish. izolyatsiya uchastkalar bo'sh xolatida, belgilangan marshrutda  strelkalarni aylanmasligini tekshirish; 30 va undan kam strelkasi bor stansiyalarda marshrutni tayyorlashda svetoforlarni ochilmasligini strelka kerakli xolatga (shu jumladan qo'riqlanadigan)qo'yilmagan bo'lsa tekshirish, (teskari marshrutlardagi svetoforlar berkilmagan bo'lsa).", "davriylik": "3 yilda bir marta", "bajaruvchi": "SHNS, SHCHU, Bekat boshlig'i(DS)", "jurnal": "AKT", "nsh": "NSH-01 7.2"},
      {"ish": "Stansiya va peregonlarda izolyatsiyalangan tutashmalar yopishganda qo'shni rels zanjirlarida qutblar almashinuvini tekshirish va ximoyalash sxemasini ishlashini tekshirish (peregonlarda 7.1 band bilan birgalikda bajarish tavsiya qilinadi.)", "davriylik": "bir yilda bir marta va oziqlantiruvchi simlar almashganda, transformatorlar\nva bog'lovchi (peremichka) almash­tirilganda yoki oziqlantiruvchi tomon kabellari ta'mirlanganda", "bajaruvchi": "SHNS,SHN", "jurnal": "Stansiyada maxsus jadvallar to'ldiriladi, peregonda SHU-79 jurnaliga yoziladi.", "nsh": "NSH-01 7.3"},
      {"ish": "Kesishmalarda va piyodalar o'tish joylarida tekshirish: yaqinlashuv uchastkalarining xaqiqiy  va hisoblangan uzunligini mosligini; stansiyadagi svetoforlarni kesishma yaqinlashuv  uchastkasi band bo'lganida ochilishini ushlab turish vaqtini, poyezdni yaqinlashuv uchastkasiga kirib kelgach, kesishma signalizatsiyasini ishlay boshlash vaqtini; signalizatsiya ishlaganidan keyin shlagbaumlarni tushish vaqtini; himoya sxemasini shuntni qisqa vaqt yo'qolishi bilan ishlab ketishini; ikki tomonlama xarakatlanadigan uchastkalarda oxirgi o'tgan poyezdni uzoq vaqt nazoratda ushlab turish sxemasi; to'suvchi signalizatsiya yoqilganda ALS kodlari o'chishi va svetofor berkilib qolishi  ko'riladi.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS,SHN", "jurnal": "Jadval", "nsh": "NSH-01 7.5"},
      {"ish": "Mavjud SMB qurilmalarini tasdiqlangan  texnik xujjatlarga muvofiqligini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS,SHN", "jurnal": "Sxemalarda belgilanadi", "nsh": "NSH-01 7.6"},
    ],
  },
  {
    bolim: "8 .SVETOFORLAR",
    ishlar: [
      {"ish": "Stansiya va peregonlarda yo'ldan turib svetaforlarning signal chiroqlarining yashil yonuvchi polosasi va yorug'lik ko'rsatkichlarining ko'rinuvchanligini tekshirish", "davriylik": "lampa linza to'plam almashganda", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 8.1"},
      {"ish": "Stansiya va peregonlarda svetaforlarning svetodiod modullari bilan jihozlangan signal chiroqlarining yashil yonuvchi polosalar va yorug'lik ko'rsatkichlarining  ko'rinuvchanligini tekshirish", "davriylik": "yiliga ikki marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 8.1"},
      {"ish": "Svetoforlarni signallar ko'rinishini stansiyaning bosh yo'lidan va peregonlarda lokomotivda tekshirish, shuningdek lokomotiv signalizatsiyasining yo'l va lokomotiv svetoforlariga mosligini tekshirish", "davriylik": "Oyda bir marta", "bajaruvchi": "SHNS,Lokomotiv mashinisti", "jurnal": "AKT,SHU-60", "nsh": "NSH-01 8.2"},
      {"ish": "Uch va to'rta signalizatsiyali svetoforlarda lampa almashtirish.Bekatning bosh yo'llari va poyezdlar to'xtamasdan o'tadigan yo'llarda, kirish, chiqish va marshrut svetoforlarini qizil, sariq, yashil ko'rinishlarida; ogohlantiruvchi va to'suvchi svetoforlarida (avtoblokirovka uchastkasidan tashqari) : Bir simlik", "davriylik": "9 haftada bir marta", "bajaruvchi": "SHN,SHNM", "jurnal": "SHU-61", "nsh": "NSH-01 8.3.1"},
      {"ish": "Bir tomonlama yo'nalishli avtoblokirovka bilan jihozlangan o'tish svetoforlarida: Bir simlik", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN,SHNM", "jurnal": "SHU-61", "nsh": "NSH-01 8.3.2"},
      {"ish": "Yonbosh yo'llarda joylashgan chiqish svetoforlarida  lampa almashtirish; kirish, chiqish, marshrutli svetoforlarda ikkinchi sariq, ikkinchi yashil ko'rinishlarida lampa almashtirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-61", "nsh": "NSH-01 8.3.4"},
      {"ish": "Taklif qiluvchi, to'suvchi, takrorlovchi svetoforlarda; yonuvchi ko'rsatkichlarda lampa almashtirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-61", "nsh": "NSH-01 8.3.5"},
      {"ish": "Svetodiod modullarini almashtirish", "davriylik": "30% svetodiod kuyganda", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-61", "nsh": "NSH-01 8.3.6"},
      {"ish": "O'zgaruvchan tokdan oziqlanuvchi svetoforlarda,yonuvchi ko'rsatkichlarda,svetodiod modullarida kuchlanishni o'lchash", "davriylik": "Lampa almashganda,svetodiod moduli almashganda", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-61", "nsh": "NSH-01 8.6"},
      {"ish": "Svetodiod modullarida kuchlanishni o'lchash", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-61", "nsh": "NSH-01 8.7"},
      {"ish": "Svetofor lampalarida kuchlanishni ikki marta pasayish sxemasida ishlaganda kuchlanishning o'zgarishini o'lchash", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN", "jurnal": "DU-46,SHU-61", "nsh": "NSH-01 8.8"},
      {"ish": "Svetofor linza to'plamini,  svetodiod modullarida yonuvchi ko'rsatkichlarni tozalash", "davriylik": "Lampa, svetodiod almashganda, ko'rinishni tekshirish natijalariga ko'ra", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 8.9"},
      {"ish": "Svetofor ichki qismni, yonuvchi ko'rsatkichlarni tekshirish va tozalash.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 8.10"},
      {"ish": "Transformator qutilarinining ichki xolatini tekshirish va tozalash, svetofor stakanini, lampa ushlagich, montaj, kontaktlarni mustaxkamligi va tozaligi, linza va oynalarni tozaligi ko'rish, zaruriy xolda ichki qismlarini  bo'yash.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 8.11"},
      {"ish": "Svetoforlar, shkaflar va boshqa qurilmalarni bo'yash.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 8.12"},
      {"ish": "Kirish, chiqish va marshrut svetoforlarida signal rele yakorining qo'yib yuborilishiga sekinlashish tushish vaqtini o'lchash.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS,SHN", "jurnal": "SHU-2 ,jadval to'ldiriladi", "nsh": "NSH-01 8.13"},
      {"ish": "Svetaforlarning miltillovchi chiroqlarining chastotasini tekshirish", "davriylik": "Miltillovchi chastotaga ta'sir etuvchi asbobolar almashganda", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 8.13.1"},
      {"ish": "Kirish, chiqish va marshrut svetoforlarni, shuningdek poyezdlarni to'xtamasdan xarakatlanishini ta'minlaydigan yo'llardagi svetoforlarni  ruxsat beruvchi ko'rinishlarini , elektr ta'minoti asosiy va zaxira fiderlariga o'tishi va qayta o'tishida berkilib qolmasligini  tekshirish", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS va ECH xodimi", "jurnal": "DU-46 AKT", "nsh": "NSH-01 8.14"},
      {"ish": "Elektr ta'minotining asosiydan va zaxira ta'minotiga va zaxiradan asosiy ta'minotga  o'tish vaqtini tekshirish", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS va ECH xodimi", "jurnal": "АКТ", "nsh": "NSH-01 8.15"},
      {"ish": "SMB qurilmalarining gabaritlarini tekshirish", "davriylik": "SMB qurilmalarini ko'chirish bo'yicha ta'mirlash ishlari olib borilganda", "bajaruvchi": "SHN, SHNM", "jurnal": "АКТ", "nsh": "NSH-01 8.16"},
    ],
  },
  {
    bolim: "9. STRELKALI O'TKAZGICHLAR",
    ishlar: [
      {"ish": "Elektoyuritma garniturasini,xarakatlanuvchi serdechnik fiksatorining tashqi holatini tozalash", "davriylik": "zaruriy xollarda kvartalda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 9.1.1"},
      {"ish": "UPM rusumli mufta va strelkali qutilarning ichki holatini,ikki simli boshqaruv sxemasida reversiv releni tekshirish", "davriylik": "bir yilda ikki marta bahorda va kuzda", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 9.1.3"},
      {"ish": "MSP tipidagi elektrodvigatellarni   strelkaning normal xolatda o'tganida va  va friksiyaga ishlab qolgandagi tok kuchini o'lchash. Uch fazalik elektrodvigatellarda friksion muftalarda itarish kuchini o'lchash.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-64", "nsh": "NSH-01 9.1.4"},
      {"ish": "Elektrodvigatellar friksiyaga ishlagandagi kuchlanishini o'lchash.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-64", "nsh": "NSH-01 9.1.4"},
      {"ish": "Elektr o'tkazgichning friksion muftasidagi va   reduktordagi moyni almashtirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 9.1.5"},
      {"ish": "Elektroyuritmani va strelka garniturasini ajratmasdan to'liq tekshirish, shuningdek elektrodvigatel cho'lg'amlarining izolyatsiya qarshiligini  korpusga nisbatan tekshirish.", "davriylik": "Bir yilda ikki marta(bahorda va kuzda)", "bajaruvchi": "SHNS,SHN", "jurnal": "SHU-2, almashtirish va ta'mirlashdan keyin", "nsh": "NSH-01 9.1.6"},
      {"ish": "Strelka elekrtoprivodini almashtirish", "davriylik": "tuzilgan rejaga asosan strelkali o'tkazgich almashganda", "bajaruvchi": "SHNS,SHN,SHNM", "jurnal": "DU-46, almashtirish jurnaliga", "nsh": "NSH-01 9.1.7"},
      {"ish": "Masofaning  RTU sexida ta'mirlangan elektrodvigatellarni almashtirish:MSP,MST", "davriylik": "MSP tipidagi elektrodvigatellar uchun uch yil va\nMST tipidagi elektrodvigatellar uchun besh yil; bahorgi va kuzgi ko'rik natijasiga ko'ra", "bajaruvchi": "SHN, SHNM", "jurnal": "Maxsus jurnal", "nsh": "NSH-01 9.1.8"},
      {"ish": "Yo'l ustasi bilan birgalikda strelkalarni avtomatik tozalash qurilmasini va sxemasiga mos ravishda ishlayotganligini tekshirish", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN,yo'l masteri", "jurnal": "DU-46", "nsh": "NSH-01 9.1.9"},
      {"ish": "Strelka yo'l qutilarining mahalliy boshqaruvda ishlatiladigan kontaktlarni va holatini tekshirish", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 9.1.10"},
      {"ish": "Elektroyuritma,strelka muftalari va qutilarini,monyovr kolonkalarini buyash", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 9.1.11"},
    ],
  },
  {
    bolim: "10.ELEKTR RELS ZANJIRLARI",
    ishlar: [
      {"ish": "Peregonda drossel va kabel ustuni (stoykasi), yo'l transformator qutisi ulagichlari butligini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 10.1"},
      {"ish": "Peregondagi rels zanjirlarining yo'l relelarida kuchlanishni o'lchash.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-62", "nsh": "NSH-01 10.3"},
      {"ish": "Lokomotiv signalizatsiyasi uchun uzatiladigan relsdagi kodli tok kuchini o'lchash.", "davriylik": "Chorakda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-64,SHU 79", "nsh": "NSH-01 10.4"},
      {"ish": "ALSning vaqt parametrlarini kodni transiliyatsiya qilayotgan rels zanjirlarida o'lchash.", "davriylik": "Transmetter relesi almashtirilganda", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 10.5"},
      {"ish": "Kabel stoykalari, yo'l qutilarining ichki qismini tekshirish, shuningdek drossel-transformatorlarning tashqi qismlarini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 10.6"},
      {"ish": "Drossel va kabel stoykasi, kabel muftalari, yo'l transformator qutilarini bo'yash.", "davriylik": "zaruriy xollarda", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 10.6"},
      {"ish": "Drossel-transformatorlarining ichki holatini tekshirish (yog' me'yori, suvning yo'qligi va asosiy chulg'amning korpusga nisbatan izolyatsiya qarshiligi, qo'shimcha chulg'am uchlarining ulanishi bo'yicha rels zanjiri tipiga qarab transformatsiya koeffitsientining muvofiqligi).", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2,SHU-79", "nsh": "NSH-01 10.6"},
      {"ish": "SMB qurilmalarining tashqi yerlash (yerga ulash) elementlarining holatini tekshirish, rele shkafi va svetoforlarga o'rnatilgan uchqunni so'ndiruvchi moslamalarni tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 10.7"},
      {"ish": "Belgilanadigan rayonlarda kontakt tarmoqlarini tekshirishda ishtirok etish, uchqunni so'ndiruvchi moslamalarning butligini, shuningdek sun'iy inshootlarning rels zanjirlariga yerlashlari to'g'ri ulanganligini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 10.7"},
      {"ish": "Rele shkaflari va svetoforlardagi diodli yerlashlarni tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 10.7"},
      {"ish": "300 m dan ortiq bo'lgan rels zanjirlarida ballast va shpalning elektr qarshiligini o'lchash.", "davriylik": "Bir yilda ikki marta (bahorda) shuningdek shpal va ballastlar yoppasiga almashtirilganda", "bajaruvchi": "SHN  va  Yo'l masteri", "jurnal": "SHU-64,SHU-62,DU-46", "nsh": "NSH-01 10.8"},
      {"ish": "Stansiyalarda nosoz rels ulagichlarini payvandlash (almashtrish).", "davriylik": "rejaga ko'ra", "bajaruvchi": "SHN yoki SHNM,elektrosvarshik", "jurnal": "SHU-2,DU-46", "nsh": "NSH-01 10.9"},
    ],
  },
  {
    bolim: "10.1. G'ildiraklar o'qlarini sanash usuli bilan yo'l uchastkalarini nazorat qilish qurilmalari.",
    ishlar: [
      {"ish": "G'ildirak o'qlarini hisoblash tizimi tashqi uskuna va yo'l qutilarining ichki qismini tekshirish. Tashqi datchiklarni tozalash va mahkamlashni tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 10.1.1"},
      {"ish": "Kabellarni ajratish joyi holatini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 10.1.2"},
      {"ish": "Yo'l qutisining ichki holatini tekshirish, kabel simlarining mahkamligini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 10.1.3"},
      {"ish": "Yo'l uchastkasida rels zanjirlarini g'ildirak o'qlarini hisoblash tizimlariga ulashda va qayta tiklashda DSP bilan birgalikda yo'l nazoratini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS,SHN,DS", "jurnal": "SHU-2", "nsh": "NSH-01 10.1.6"},
    ],
  },
  {
    bolim: "11.BOSHQARUV APPARATLARI",
    ishlar: [
      {"ish": "Pult, tablo, manyovr kolonkasini xolatini tekshirish(elementlarning mustaxkam qotirilganligi, buragichlar va knopkalarni yengil yurishi, xisoblagich knopkalarni xolati, itaruvchi prujinalarni qattiqligi, qo'ng'iroq va jezl kalitini ishlashi, kontaktlar xolati, shtepsel razyomlari butligi, montaj va uni izolyatsiyasi butligi, simlarni maxkamligi , qulflar butligi)", "davriylik": "Bir oyda bir marta", "bajaruvchi": "SHN", "jurnal": "DU-46", "nsh": "NSH-01 11.1.1"},
      {"ish": "Kommutator, tugmalar va buragichlarning holatini tekshirish, zarur hollarda sozlash.", "davriylik": "Uch yilda bir marta", "bajaruvchi": "SHN, RTU", "jurnal": "DU-46", "nsh": "NSH-01 11.1.2"},
    ],
  },
  {
    bolim: "11.6. Avtomatlashtirilgan ish o'rinlari uchun uskuna (ARM) MPTS.",
    ishlar: [
      {"ish": "Monitorni sozlash va rostlash.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 11.6.2"},
      {"ish": "Raz'yemlar va ulanish shnurlari (tashqi ulanishlarni) mahkamligining ishonchliligini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 11.6.3"},
      {"ish": "Klaviatura va \"sichqoncha\" manipulyatorini tozalash.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2,DU-46", "nsh": "NSH-01 11.6.4"},
      {"ish": "Yechmagan holda printerni tozalash.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 11.6.5"},
      {"ish": "Tizimli kompyuter bloklarini ichki qismini tozalash.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2,DU-46", "nsh": "NSH-01 11.6.6"},
      {"ish": "Asosiy ARM DSP (DNC) dan zaxiraga o'tishning to'g'riligini tekshirish va zaxiradan asosiyga o'tishda ishlashini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNS,DSP(DNS)", "jurnal": "SHU-2,DU-46", "nsh": "NSH-01 11.6.7"},
    ],
  },
  {
    bolim: "11.7. Apparat-dasturiy vositalar asosida SMB qurilmalarini boshqarish va nazorat qilishning texnik vositalari (MPTS).",
    ishlar: [
      {"ish": "Shkaflarni tashqi tozalash (kompleks boshqarish), old va montaj tomonidan tekshirish, tashqi ulanishlar razyomlari mustahkamligining ishonchliligini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 11.7.2"},
      {"ish": "DSP (DNC) bilan birgalikda ishlayotgan protsessor modulidan zaxiraga o'tishning to'g'riligini tekshirish va zaxiradan asosiyga o'tishda ishlashini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNS,DSP(DNS)", "jurnal": "DU-46,SHU-2", "nsh": "NSH-01 11.7.3"},
    ],
  },
  {
    bolim: "Boshqarish va nazorat qilish obyektlari bilan juftlashtirish qurilmalari:",
    ishlar: [
      {"ish": "Modullar, shkaflar va boshqa asbob-uskunalarni, kabel (raz'yemlar) ulanishlarini, yerga ulagichlar mahkamligining ishonchliligini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 17.7.5"},
      {"ish": "Modullarni, faol platalarni zaxira platalariga o'tkazib yoqish va orqaga qaytarish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 17.7.6"},
      {"ish": "ARM monitorida SMB qurilmalarining amaldagi holatining to'g'riligini tekshirish. ARM–DSPdan SMB tashqi qurilmalarining faoliyatini tekshirish.", "davriylik": "Dasturiy ta'minot versiyalari va kompleks boshqaruvchisining texnik vositalari almashtirilgandan so'ng", "bajaruvchi": "SHNS,uchastka boshlig'i,DSP", "jurnal": "AKT", "nsh": "NSH-01 17.7.8"},
      {"ish": "ZIP (zaxira) to'plamining mavjudligi va holatini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS", "jurnal": "SHU-2", "nsh": "NSH-01 11.7.9"},
    ],
  },
  {
    bolim: "11.8. Apparat-dasturiy vositalar (MPTs) asosida SMB qurilmalarining dasturiy ta'minoti (PO).",
    ishlar: [
      {"ish": "Tizim soatlarining vaqt va sanasini joriy vaqt va sana bilan muvofiqligini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHNS,SHN", "jurnal": "SHU-2", "nsh": "NSH-01 11.8.2"},
    ],
  },
  {
    bolim: "12. SMB ASBOBLARI",
    ishlar: [
      {"ish": "Isitiladigan xonalardagi asboblar va shtepsel rozetkalarini montaj tomonidan tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 12.1"},
      {"ish": "Isitilmaydigan xonalarda, shkaf va yo'l qutilarida asboblar va shtepsel rozetkalarini montaj tomonidan tekshirish. kesishmaga yaqinlashuvini ogoxlantiruvchi signal, liniya, yo'l relesi takrorlovchisi relesining qoldiq kuchlanishini o'lchash, uchqunni so'ndirish uchun qo'yilgan varistorni xolatini ko'rish.", "davriylik": "Bir yilda ikki marta(bahor va kuzda)", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 12.1"},
      {"ish": "Puskovoy, transimitterlar, impulsli relelar,  kodli rele yacheykalari, deshifrator yacheykalari va deshifrator bloklarini xolatini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 12.2"},
      {"ish": "Elektrolitli kondensatorlarda,deshifrator yacheykalari,kodli avtoblokirovka deshifrator bloklarida kuchlanishni o'lchash/", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-62", "nsh": "NSH-01 12.3"},
      {"ish": "Tenglashuvchi (vyravnitel) va yashin qaytargichlarning holatini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 12.4"},
      {"ish": "SMB asboblarini va boshqa uskuna­larni almashtirish.", "davriylik": "belgilangan muddatda", "bajaruvchi": "SHNS,SHN", "jurnal": "DU-46,almashtirish jurnali", "nsh": "NSH-01 12.5"},
    ],
  },
  {
    bolim: "13. Kesishmaning avtomatik signalizatsiyasi, avtomatik shlagbaumlar, to'siq qurilmalari va piyodalar o'tish joyi signalizatsiyasi.",
    ishlar: [
      {"ish": "Temir yo'l kesishmasi svetoforlari va to'suvchi svetoforlarning o'zgaruvchan va o'zgarmas tokda ishlashini tekshirish, shuningdek kesishmadagi to'suvchi signalizatsiyani poyezd va manyovr signallari bilan uzviy birgalikda ishlaydigan svetoforlarda tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN,yo'l masteri yoki brigadiri", "jurnal": "PU-67,SHU-2", "nsh": "NSH-01 13.2"},
      {"ish": "UZP qurilmasidagi to'suvchi moslamalarning ishini kompleks tekshirishda ishtirok etish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHNS,yo'l masteri yoki brigadiri", "jurnal": "PU-67,SHU-2", "nsh": "NSH-01 13.2"},
      {"ish": "Qurilmalarni sozligi va ishlashini kompleks tekshirish, xamda ayrim nosoz kisimlarini almashtirish.", "davriylik": "Bir yilda bir marta elektroprivodni yechmasdan, uch yilda bir marta elektroprivodni yechib tekshiraladi", "bajaruvchi": "SHNS,SHN, SHNM", "jurnal": "PU-67,SHU-2", "nsh": "NSH-01 13.4"},
      {"ish": "Shlagbaum elektroyuritmalarida elektrodvigatellarni almashtirish (13.4-bandi bilan birgalikda bajariladi).", "davriylik": "Uch yilda bir marta", "bajaruvchi": "SHN", "jurnal": "Almashtirish jurnali", "nsh": "NSH-01 13.5"},
      {"ish": "Elektrodvigatellarning kuchlanishini UZP qurilmasining qopqog'ini normal holatda ko'tarish, tushirish va friktsiyaga ishlaganda tekshirish;\nUZP qopqog'ining to'liq ko'tarilish vaqtini va friktsiya ishlayotganda UZP elektrodvigatellarini o'chirish vaqtini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "PU-67,SHU-2", "nsh": "NSH-01 13.7"},
      {"ish": "Nazorat baza blokining (BBK) chiqish parametrlarini tekshirish va transport vositalarini aniqlash datchiklarining (DTR) ish faoliyatini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN, SHNM", "jurnal": "PU-67,SHU-2", "nsh": "NSH-01 13.8"},
      {"ish": "Shlagbaum va UZP elektroyuritmalaridagi elektrodvigatellarni almashtirish:\nO'zgarmas tokli elektrodvigatel:", "davriylik": "Uch yilda bir marta", "bajaruvchi": "SHN", "jurnal": "PU-67, almashtirish jurnali", "nsh": "NSH-01 13.9"},
    ],
  },
  {
    bolim: "15.NAZORAT – GABARIT QURILMALARI (KGU, UKSPS)",
    ishlar: [
      {"ish": "Marshrut tayyorlanganda nazorat–gabarit qurilmalari (KGU, UKSPS)ning ishlashini kabel yashigidagi saqlagichni olib tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "DU-46", "nsh": "NSH-01 15.1"},
      {"ish": "Nazorat relesida kuchlanishni o'lchash.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 15.2"},
      {"ish": "Yo'l brigadiri bilan birgalikda KGU, UKSPS qurilmalarining nazorat simlarini va metall konstruksiyalar holatini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNM , PD", "jurnal": "SHU-2", "nsh": "NSH-01 15.3"},
      {"ish": "KGU, UKSPS qurilmalarining nazorat simlarida sxemadan uzilgan holatda izolyatsiya qarshiligini o'lchash, kabel yashig'ini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 15.4"},
      {"ish": "UKSPS datchiklarini nazorat qilish sxemasining ishlashini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2 DU-46", "nsh": "NSH-01 15.5"},
    ],
  },
  {
    bolim: "17. KABEL TIZIMI, ICHKI MONTAJ",
    ishlar: [
      {"ish": "Kabel muftalarini ochib tekshirish.", "davriylik": "Bir yilda ikki bor(Bahorda va kuzda)", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 17.1.1"},
      {"ish": "Kabel tolalarini  izolyatsiya qarshiligini yerga nisbatan minimal o'chirish orqali o'lchash, shu jumladan zaxiradagilarini xam.", "davriylik": "Bir yilda ikki bor(Bahorda va kuzda)", "bajaruvchi": "SHNS,SHN, SHNM", "jurnal": "SHU-64,SHU-79", "nsh": "NSH-01 17.1.2"},
      {"ish": "Kabel tolalarining izolyatsiya qarshiligini yerga va bir – biriga nisbatan o'lchash.", "davriylik": "Qurilma ekspluatatsiyaga tushirilishdan oldin, kabel ta'mir. yoki almashgan keyin)", "bajaruvchi": "SHNS,RTU", "jurnal": "SHU-67", "nsh": "NSH-01 17.1.3"},
      {"ish": "Drenaj va katodli himoya vositalarining holatini tekshirish, drenaj va kabel qobig'idagi tok kuchini yerga nisbatan o'lchash.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "Ximoya vositasi pasporti", "nsh": "NSH-01 17.1.4"},
      {"ish": "Kabel qobig'idagi tok kuchini yerga nisbatan relslarda va nazorat nuqtalarida o'lchash.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN, RTU ishchisi", "jurnal": "Maxsus jurnal", "nsh": "NSH-01 17.1.5"},
      {"ish": "Kabel trassasi va kabel jelobalarini ko'rish: Stansiyada", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 17.1.6"},
      {"ish": "Peregonda", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 17.1.6"},
      {"ish": "Stansiya va peregonlarda yerlatish signalizatori tomonidan nazorat qilinmaydigan kabel tolalari va montajlarda izolyatsiya qarshiligini o'lchash.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-62,SHU-64", "nsh": "NSH-01 17.1.7"},
      {"ish": "Yerga nisbatan elektr ta'minot zanjirlarining izolyatsiya qarshiligini nazorat qilish sxemalarini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 17.1.9"},
      {"ish": "Apparat - dasturiy vositalar bilan jihozlangan SMB qurilmalarini raz'yomlarini, ulovchi shnurlarini va yerga o'tkazgichlarini mahkamlanishini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 17.10"},
      {"ish": "Yerga nisbatan kabel ekran izolyatsiyasi qarshiligini o'lchash, apparat - dasturiy vositalari bilan jihozlangan SMB qurilmalari ekranining butunligini tekshirish.", "davriylik": "Bir yilda ikki bor", "bajaruvchi": "SHNS,SHN", "jurnal": "SHU-2 DU-46", "nsh": "NSH-01 17.1.11"},
    ],
  },
  {
    bolim: "18. ELEKTR TA'MINOTI QURILMALARI",
    ishlar: [
      {"ish": "Elektr kuchlanishi bilan quvvatlanadigan qurilmalarni elementlari va asboblarini ko'rib, tekshirish imkoniyati borlarini tashqi tomondan tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 18.1.2"},
      {"ish": "Kuchlanishni ta'minlovchi qurilmalarda to'g'rilagichlarni, akkumulyator batareyalarini kuchlanishini avtomatik tarzda sozlab turuvchi bloklarni tekshirish.", "davriylik": "Ikki yilda bir marta", "bajaruvchi": "SHNS,RTU", "jurnal": "SHU-2", "nsh": "NSH-01 18.1.3"},
      {"ish": "To'g'rilagichni xolatini tekshirish va to'g'rilangan kuchlanishni o'lchash", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN", "jurnal": "SHU-63 SHU-2", "nsh": "NSH-01 18.1.4"},
      {"ish": "Bufer rejimida ishlaydigan to'g'rilagichlardagi to'g'rilangan kuchlanishni o'lchash.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-63", "nsh": "NSH-01 18.1.5"},
      {"ish": "Stansiya va peregonlarda o'zgaruvchan tokli rezerv ta'minotning mavjudligi va sozligini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-62 SHU-2", "nsh": "NSH-01 18.1.6"},
      {"ish": "Rezerv kuchlanishidan, kuchlanish o'zgartirgichining ishlashini sinov yo'li bilan tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 18.1.7"},
      {"ish": "EM postlaridagi kirish panelida va kabel qutilarida asosiy va zaxira fiderlarida kuchlanishni o'lchash.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN,ECH", "jurnal": "SHU-62 SHU-2", "nsh": "NSH-01 18.1.8"},
      {"ish": "EM postlarida kirish panellari, rele shkaflarida va kabel qutilarida saqlagichlar va avtomatik o'chiruvchi moslamalardan oqib o'tuvchi tok kuchini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 18.1.8"},
    ],
  },
  {
    bolim: "18.2.AKKUMULYATORLAR",
    ishlar: [
      {"ish": "Akkumulyatorlar holatini, har bir akkumulyatorda kuchlanishni va elektrolit zichligini 12 A yuklama probnigi orqali o'zgaruvchan tok o'chirilgan holatda o'lchash; Butun sistema uchun", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS", "jurnal": "SHU-63", "nsh": "NSH-01 18.2.1"},
      {"ish": "Shamollatish qurilmasining holati va ishlashini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "SHNS", "jurnal": "SHU-2", "nsh": "NSH-01 18.2.2"},
    ],
  },
  {
    bolim: "UZLUKSIZ QUVVAT QURILMALARI (UBP)",
    ishlar: [
      {"ish": "UBP, akkumulyatorlarni tashqi tekshirish va tashqi tozalash, akkumulyatorlarda kuchlanishni tekshirish, shamollatgichlarining ishlashini tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-01 18.2.4"},
      {"ish": "SMB qurilmalarining tashqi elektr ta'minoti o'chirilgan paytda UBPdan ishlashini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHNS,SHN", "jurnal": "SHU-2", "nsh": "NSH-01 18.2.5"},
    ],
  },
  {
    bolim: "18.3.DIZEL-GENERATOR AGREGAT",
    ishlar: [
      {"ish": "Tasmalarni tortilganligi va yaxshi joylashtirilganligini tekshirish, klapandagi oral, moy almashtirish, qo'yilgan detallarni mahkamligini tekshirish va qismlarni tozalash; filtrlarni yuvish; generator va starterlarni tekshirish.", "davriylik": "Kvartalda bir marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 18.3.2"},
      {"ish": "Rele, knopkalar, rubilniklar holatini tekshirish, kontakt prujinalarni sozlash va tozalash.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 18.3.3"},
      {"ish": "DGA ni yoqilishini yuklama bilan tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN", "jurnal": "DU-46", "nsh": "NSH-01 18.3.4"},
      {"ish": "Qurilmaning texnik ko'rigi:\nYoqilg'i sistemasini, yoqilg'i tizimini tekshirish; yopiq sovutish tizimini yuvish va suvni almashtirish; moylash tizimini tekshirish.", "davriylik": "Bir yilda bir marta", "bajaruvchi": "Tayinlangan xodim", "jurnal": "SHU-2", "nsh": "NSH-01 18.3.5"},
    ],
  },
  {
    bolim: "18.4.XIMOYA QURILMALAR",
    ishlar: [
      {"ish": "Saqlagichlarning holatini tekshirish, kuyish nazorat sxemasining ishlashini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 18.4.1"},
      {"ish": "Saqlagichlarni (holatidan qat'iy nazar) TTU da tekshirilgan saqlagichlarga almashtirish.", "davriylik": "6-ilovada ko'rsatilgan muddatda", "bajaruvchi": "SHN", "jurnal": "MAXSUS JURNAL", "nsh": "NSH-01 18.4.2"},
      {"ish": "EM posti, rele budkasi, kesishma konteynerlari, shkaflar va boshqa SMB inshootlarining ko'rinadigan yerlatgich qurilmalarini tekshirish.", "davriylik": "Bir yilda ikki marta", "bajaruvchi": "SHN", "jurnal": "SHU-2", "nsh": "NSH-01 18.4.4"},
      {"ish": "Chaqmoqdan himoya qiluvchi qurilmalarni sozlash va tekshirish.", "davriylik": "Bir yilda bir marta(bahorda chaqmoq bo'lishi mavsumi oldidan)", "bajaruvchi": "SHN,RTU", "jurnal": "SHU-79 peregonda,SHU-45", "nsh": "NSH-01 18.4.4"},
    ],
  },
  {
    bolim: "19.TEMIRBETON KONSTRUKSIYALARI",
    ishlar: [
      {"ish": "Barcha uchastkalardagi konstruksiyalarning yer usti qismini tekshirish va baholash.", "davriylik": "Uch yilda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "MAXSUS JURNAL", "nsh": "NSH-01 19.1"},
      {"ish": "Potensiallar farqini \"rels - yer\" tizimida o'lchash.", "davriylik": "Uch yilda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "MAXSUS JURNAL", "nsh": "NSH-01 19.2"},
      {"ish": "O'zgarmas tokli elektrlashtirilgan yo'llarning katodli zonalarida joylashgan yer osti konstruksiyalarini holatini tekshirish va baholash.", "davriylik": "Tanlash yo'li bilan 10 yil ishlagandan keyin.", "bajaruvchi": "SHN, SHNM", "jurnal": "MAXSUS JURNAL", "nsh": "NSH-01 19.3"},
    ],
  },
  {
    bolim: "ALOQA",
    ishlar: [
      {"ish": "Operativ va GGS aloqani tekshirish va tozalash", "davriylik": "Bir oyda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-17 8.3"},
      {"ish": "Optik aloqa,Telefoniya ,Ithernet va boshqa aloqa qurilmalarining elektr ta'minotini tekshirish", "davriylik": "Bir oyda bir marta", "bajaruvchi": "SHN, SHNM", "jurnal": "SHU-2", "nsh": "NSH-17 7.16"},
    ],
  },
];